# Hardware gate; run under julia_metal. --generate explicitly regenerates the
# compile-only inventory after a reviewed engine/dependency change. Ordinary
# test runs never update it. There is no instrumentation in production code.
import Metal
using Test, JSON
using BeatEngineMetalBundle

const Bundle = BeatEngineMetalBundle

function observed_metal_signatures()
    observed = Set{Tuple{Any,Any}}()
    function observe(job)
        types = job.source.specTypes.parameters
        push!(observed, (types[1].instance, Tuple{types[2:end]...}))
    end
    empty!(Metal.kernel_instances)
    Base.ScopedValues.with(Metal.GPUCompiler.compile_hook => observe) do
        mktempdir() do directory
            tiny = joinpath(directory, "tiny.msh")
            write(tiny, Bundle.WORKLOAD_MESH)
            fixtures = joinpath(@__DIR__, "..", "test_meshes")
            for (symmetry, mesh, scale) in (
                ("off", tiny, 1.0),
                ("off", joinpath(fixtures, "sample.msh"), 0.001),
                ("x", joinpath(fixtures, "sample_half.msh"), 0.001),
                ("xy", joinpath(fixtures, "sample_quarter.msh"), 0.001),
            ), order in (1, 2, 4)
                request = Dict{String,Any}(
                    "schema_version" => 2, "beat_engine_backend" => "metal",
                    "frequencies_hz" => [1000.0, 2000.0],
                    "config" => Dict{String,Any}(
                        "mesh_file" => mesh, "scale_factor" => scale,
                        "distance" => 2.0, "axial_offset" => 0.0,
                        "step_size" => 5.0, "min_angle" => 0.0, "max_angle" => 180.0,
                        "freq_min" => 1000.0, "freq_max" => 2000.0, "freq_count" => 2,
                        "tag_throat" => 2, "rho" => 1.2041, "sound_speed" => 343.0,
                        "symmetry" => symmetry, "source_motion" => "normal",
                        "quadrature_order" => order, "singular_order" => 4,
                        "spherical_sampling_enabled" => true,
                        "spherical_sampling_points" => 37 * 72,
                        "spherical_grid" => Dict("theta_count" => 37, "phi_count" => 72,
                                                 "theta_max_deg" => 180.0),
                    ),
                )
                event_path = joinpath(directory, "events.jsonl")
                open(event_path, "w") do io
                    redirect_stdout(io) do
                        Bundle.solve_request(JSON.parse(JSON.json(request)))
                    end
                end
                events = [JSON.parse(line) for line in readlines(event_path) if startswith(line, "{")]
                @test count(event -> get(event, "type", "") == "result", events) == 2
                @test any(event -> get(event, "type", "") == "completed", events)
            end
        end
    end
    return observed
end

function write_metal_signatures(path, signatures)
    lines = String[]
    for (f, tt) in signatures
        line = "    (" * repr(typeof(f)) * ".instance, " * repr(tt) * "),"
        line = replace(line, r"(?<![.\w])GPUArrays\." => "Metal.GPUArrays.",
                             r"(?<![.\w])KernelAbstractions\." => "Metal.KernelAbstractions.")
        push!(lines, line)
    end
    open(path, "w") do io
        println(io, "# Generated by julia_local/tests/metal_kernel_coverage_tests.jl --generate.")
        println(io, "# Float32 source-entry exterior requests; see the bundle README for coverage.")
        println(io, "[")
        foreach(line -> println(io, line), sort!(lines))
        println(io, "]")
    end
end

@testset "Metal source-entry kernel signature coverage" begin
    # A hardware qualification must fail rather than pass a skipped workload.
    @test Metal.functional()
    observed = observed_metal_signatures()
    @test !isempty(observed)
    if "--generate" in ARGS
        output = findfirst(arg -> startswith(arg, "--inventory-output="), ARGS)
        path = output === nothing ? joinpath(dirname(pathof(Bundle)), "MetalKernelSignatures.jl") :
            split(ARGS[output], "="; limit=2)[2]
        write_metal_signatures(path, observed)
        @info "Generated BEAT Metal kernel inventory" signatures=length(observed)
    else
        expected = Set(Bundle.metal_kernel_signatures())
        missing = setdiff(observed, expected)
        for (f, tt) in missing
            @error "Production Metal kernel missing from precompile inventory" function_type=typeof(f) argument_types=tt
        end
        @test isempty(missing)
        @info "BEAT Metal kernel inventory coverage" observed=length(observed) inventory=length(expected)
    end
end
